<template><section class="transfer"><p class="eyebrow">STUDIO / CONTENT TRANSFER</p><h1 class="page-heading">内容导入导出</h1><p class="muted intro">导出全部文章、元数据和本地图片；也可以导入 OpenPanda ZIP 或单个 Markdown 文件。</p><div class="cards"><article><span>01</span><h2>导出全部内容</h2><p>下载包含 manifest、文章 Markdown 和图片资源的 ZIP 包。</p><button class="action-button" :disabled="!!busy" @click="download">{{ busy === 'export' ? '正在打包…' : '下载 ZIP' }}</button></article><article><span>02</span><h2>导入 ZIP</h2><p>导入 OpenPanda 导出包，图片路径会自动恢复。</p><label class="action-button">{{ busy === 'zip' ? '正在导入…' : '选择 ZIP' }}<input type="file" accept=".zip" :disabled="!!busy" @change="choose($event, 'zip')" /></label></article><article><span>03</span><h2>导入 Markdown</h2><p>支持 YAML Front Matter；无标题文件会被拒绝。</p><label class="action-button">{{ busy === 'md' ? '正在导入…' : '选择 Markdown' }}<input type="file" accept=".md,text/markdown" :disabled="!!busy" @change="choose($event, 'md')" /></label></article></div><div v-if="message" class="result" role="status">{{ message }}</div></section></template>
<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { exportContent, importMarkdown, importZip, type TransferResult } from '@/api/modules/contentTransfer'
const busy = ref<'export' | 'zip' | 'md' | null>(null); const message = ref('')
async function download() { busy.value = 'export'; try { const r = await exportContent(); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = `openpanda-export-${new Date().toISOString().slice(0, 10)}.zip`; a.click(); URL.revokeObjectURL(url); ElMessage.success('导出完成') } catch { ElMessage.error('导出失败') } finally { busy.value = null } }
async function choose(event: Event, type: 'zip' | 'md') { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; busy.value = type; message.value = ''; try { const r = type === 'zip' ? await importZip(file) : await importMarkdown(file); const result: TransferResult = r.data.data; message.value = `导入完成：新增 ${result.articles_created} 篇文章，导入 ${result.resources_imported} 个资源。`; ElMessage.success('导入完成') } catch { message.value = '导入失败，请检查文件格式和服务器日志'; ElMessage.error('导入失败') } finally { busy.value = null; input.value = '' } }
</script>
<style scoped>.transfer{max-width:960px;margin:auto}.intro{max-width:620px;font-size:17px;line-height:1.9}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:48px}.cards article{min-height:280px;padding:24px;display:flex;flex-direction:column;align-items:flex-start;border:1px solid var(--border-subtle);background:var(--surface-panel);border-radius:8px}.cards article>span{color:var(--link-foreground);font:12px var(--font-mono)}.cards h2{margin:28px 0 12px;font-family:var(--font-heading);font-size:22px;line-height:1.5}.cards p{color:var(--foreground-secondary);font-size:14px;line-height:1.8}.cards .action-button{margin-top:auto}.action-button{cursor:pointer}.action-button input{position:absolute;width:1px;height:1px;opacity:0}.result{margin-top:28px;padding:16px 20px;border-left:3px solid var(--color-success);background:var(--surface-panel)}@media(max-width:800px){.cards{grid-template-columns:1fr}.cards article{min-height:0}.cards .action-button{margin-top:24px}}</style>